<?php
/**
 * Plugin Name: HS Media Upload Accelerator
 * Description: Keeps editor preview sizes synchronous and creates layout sizes after the upload response.
 * Version: 2.0.0
 * Author: Manacost
 *
 * @package Manacost
 */

declare(strict_types=1);

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * Moves non-critical Newspaper image generation out of the upload response.
 */
final class HS_Media_Upload_Accelerator {
	private const HOOK         = 'hs_media_upload_accelerator_generate_subsizes';
	private const GROUP        = 'hs-media-upload-accelerator';
	private const MAX_ATTEMPTS = 3;

	/**
	 * Sizes needed immediately by the media editor.
	 * Every other registered size is generated by wp_update_image_subsizes().
	 *
	 * @var string[]
	 */
	private const IMMEDIATE_SIZES = array(
		'thumbnail',
		'medium',
		'medium_large',
	);

	/**
	 * Attachments waiting to be handed to the background worker.
	 *
	 * @var array<int, int>
	 */
	private static array $pending_attachments = array();

	/**
	 * Attachments whose complete metadata is not ready yet.
	 *
	 * @var array<int, bool>
	 */
	private static array $deferred_attachments = array();

	/**
	 * Register upload acceleration hooks.
	 */
	public static function boot(): void {
		add_filter( 'intermediate_image_sizes_advanced', array( __CLASS__, 'filter_sizes' ), 20, 3 );
		add_filter( 'big_image_size_threshold', '__return_false', 20 );
		add_filter( 'wp_generate_attachment_metadata', array( __CLASS__, 'queue_after_metadata' ), 100, 3 );
		add_filter( 'hs_local_image_optimizer_should_queue', array( __CLASS__, 'filter_local_optimizer_queue' ), 10, 4 );
		add_action( 'shutdown', array( __CLASS__, 'flush_pending_queue' ), 10 );
		add_action( self::HOOK, array( __CLASS__, 'generate_deferred_subsizes' ), 10, 2 );
		add_action( 'plugins_loaded', array( __CLASS__, 'prune_upload_hooks' ), PHP_INT_MAX );
	}

	/**
	 * Keep only editor preview sizes in the upload request.
	 *
	 * @param mixed                $sizes Registered image sizes.
	 * @param array<string, mixed> $metadata Existing attachment metadata.
	 * @param int                  $attachment_id Attachment post ID.
	 *
	 * @return mixed
	 */
	public static function filter_sizes( $sizes, array $metadata = array(), int $attachment_id = 0 ) {
		unset( $metadata );

		if (
			( defined( 'HS_MEDIA_UPLOAD_ALL_SIZES' ) && HS_MEDIA_UPLOAD_ALL_SIZES )
			|| ! self::is_upload_request()
			|| ! is_array( $sizes )
		) {
			return $sizes;
		}

		$filtered_sizes = array_intersect_key( $sizes, array_flip( self::IMMEDIATE_SIZES ) );
		if ( $attachment_id > 0 && count( $filtered_sizes ) < count( $sizes ) ) {
			self::$deferred_attachments[ $attachment_id ] = true;
		}

		return $filtered_sizes;
	}

	/**
	 * Queue the attachment when deferred sizes remain.
	 *
	 * @param mixed  $metadata Attachment metadata.
	 * @param int    $attachment_id Attachment post ID.
	 * @param string $context Metadata generation context.
	 *
	 * @return mixed
	 */
	public static function queue_after_metadata( $metadata, int $attachment_id, string $context = 'create' ) {
		if (
			'create' !== $context
			|| ! self::is_upload_request()
			|| ! is_array( $metadata )
			|| $attachment_id <= 0
			|| ! function_exists( 'wp_attachment_is_image' )
			|| ! wp_attachment_is_image( $attachment_id )
			|| ! self::has_deferred_sizes_missing( $metadata )
		) {
			return $metadata;
		}

		self::$deferred_attachments[ $attachment_id ] = true;
		self::$pending_attachments[ $attachment_id ]  = $attachment_id;

		return $metadata;
	}

	/**
	 * Keep the local optimizer out of the initial request. It is queued after
	 * WordPress finishes every deferred Newspaper size.
	 *
	 * @param mixed                $should_queue Existing decision.
	 * @param array<string, mixed> $metadata Attachment metadata.
	 * @param int                  $attachment_id Attachment post ID.
	 * @param string               $context Metadata generation context.
	 *
	 * @return bool
	 */
	public static function filter_local_optimizer_queue(
		$should_queue,
		array $metadata,
		int $attachment_id,
		string $context = 'create'
	): bool {
		unset( $metadata, $context );

		return isset( self::$deferred_attachments[ $attachment_id ] ) ? false : (bool) $should_queue;
	}

	/**
	 * Schedule collected attachments after the response is sent.
	 */
	public static function flush_pending_queue(): void {
		$attachment_ids            = self::$pending_attachments;
		self::$pending_attachments = array();

		foreach ( $attachment_ids as $attachment_id ) {
			self::enqueue( $attachment_id, 0 );
		}
	}

	/**
	 * Generate all sizes omitted from the initial upload request.
	 *
	 * @param int $attachment_id Attachment post ID.
	 * @param int $attempt Retry number.
	 */
	public static function generate_deferred_subsizes( int $attachment_id, int $attempt = 0 ): void {
		if (
			$attachment_id <= 0
			|| ! function_exists( 'wp_attachment_is_image' )
			|| ! wp_attachment_is_image( $attachment_id )
			|| ! function_exists( 'wp_update_image_subsizes' )
		) {
			return;
		}

		self::$deferred_attachments[ $attachment_id ] = true;

		$result = wp_update_image_subsizes( $attachment_id );
		unset( self::$deferred_attachments[ $attachment_id ] );
		if ( is_wp_error( $result ) && $attempt + 1 < self::MAX_ATTEMPTS ) {
			self::enqueue( $attachment_id, $attempt + 1, 60 );
			return;
		}

		if ( is_wp_error( $result ) ) {
			update_post_meta(
				$attachment_id,
				'_hs_media_upload_accelerator_error',
				substr( $result->get_error_message(), 0, 500 )
			);
			return;
		}

		self::queue_local_optimizer( $attachment_id );
	}

	/**
	 * Remove disabled third-party processing from the upload path.
	 */
	public static function prune_upload_hooks(): void {
		self::remove_class_callbacks(
			'add_attachment',
			array(
				'AIOSEO\\Plugin\\Lite\\Admin\\PostSettings',
				'AIOSEO\\Plugin\\Common\\Admin\\PostSettings',
			)
		);

		$imagify_settings = get_option( 'imagify_settings', array() );
		if ( is_array( $imagify_settings ) && empty( $imagify_settings['auto_optimize'] ) ) {
			foreach ( array( 'add_attachment', 'wp_generate_attachment_metadata', 'wp_update_attachment_metadata' ) as $hook ) {
				self::remove_class_callbacks( $hook, array( 'Imagify_Auto_Optimization' ) );
			}
		}
	}

	/**
	 * Schedule a deferred-size generation attempt.
	 *
	 * @param int $attachment_id Attachment post ID.
	 * @param int $attempt Retry number.
	 * @param int $delay Delay in seconds.
	 */
	private static function enqueue( int $attachment_id, int $attempt, int $delay = 0 ): void {
		$args = array( $attachment_id, $attempt );

		if ( function_exists( 'as_enqueue_async_action' ) && 0 === $delay ) {
			// Action Scheduler uniqueness ignores callback arguments in its DB
			// store, so it must stay disabled for per-attachment burst jobs.
			as_enqueue_async_action( self::HOOK, $args, self::GROUP, false );
			return;
		}

		if ( function_exists( 'as_schedule_single_action' ) ) {
			as_schedule_single_action( time() + $delay, self::HOOK, $args, self::GROUP, false );
			return;
		}

		if ( ! function_exists( 'wp_schedule_single_event' ) ) {
			return;
		}

		if ( function_exists( 'wp_next_scheduled' ) && wp_next_scheduled( self::HOOK, $args ) ) {
			return;
		}

		wp_schedule_single_event( time() + max( 1, $delay ), self::HOOK, $args );
	}

	/**
	 * Hand a complete attachment to the local image optimizer.
	 *
	 * @param int $attachment_id Attachment post ID.
	 */
	private static function queue_local_optimizer( int $attachment_id ): void {
		if ( class_exists( 'HS_Local_Image_Optimizer_WordPress' ) ) {
			HS_Local_Image_Optimizer_WordPress::queue_attachment( $attachment_id );
		}
	}

	/**
	 * Determine whether registered non-critical sizes are absent.
	 *
	 * @param array<string, mixed> $metadata Attachment metadata.
	 *
	 * @return bool
	 */
	private static function has_deferred_sizes_missing( array $metadata ): bool {
		if ( ! function_exists( 'wp_get_registered_image_subsizes' ) ) {
			return false;
		}

		$registered_sizes = wp_get_registered_image_subsizes();
		$generated_sizes  = isset( $metadata['sizes'] ) && is_array( $metadata['sizes'] ) ? $metadata['sizes'] : array();
		$immediate_sizes  = array_flip( self::IMMEDIATE_SIZES );

		foreach ( array_keys( $registered_sizes ) as $size_name ) {
			if ( ! isset( $immediate_sizes[ $size_name ] ) && ! isset( $generated_sizes[ $size_name ] ) ) {
				return true;
			}
		}

		return false;
	}

	/**
	 * Detect WordPress media upload endpoints without mutating request data.
	 *
	 * @return bool
	 */
	private static function is_upload_request(): bool {
		$script_name = isset( $_SERVER['SCRIPT_FILENAME'] )
			? basename( sanitize_text_field( wp_unslash( $_SERVER['SCRIPT_FILENAME'] ) ) )
			: '';
		if ( 'async-upload.php' === $script_name ) {
			return true;
		}

		if ( defined( 'REST_REQUEST' ) && REST_REQUEST ) {
			$request_uri = isset( $_SERVER['REQUEST_URI'] )
				? sanitize_text_field( wp_unslash( $_SERVER['REQUEST_URI'] ) )
				: '';
			// phpcs:disable WordPress.Security.NonceVerification.Recommended -- Read-only route detection; core validates upload authorization.
			$rest_route = isset( $_GET['rest_route'] ) && is_scalar( $_GET['rest_route'] )
				? sanitize_text_field( (string) wp_unslash( $_GET['rest_route'] ) )
				: '';
			// phpcs:enable WordPress.Security.NonceVerification.Recommended
			if ( preg_match( '#/wp-json/wp/v2/media/?(?:\?|$)#', $request_uri ) || '/wp/v2/media' === rtrim( $rest_route, '/' ) ) {
				return true;
			}
		}

		if ( ! function_exists( 'wp_doing_ajax' ) || ! wp_doing_ajax() ) {
			return false;
		}

		// phpcs:disable WordPress.Security.NonceVerification.Recommended -- Read-only route detection; core validates upload authorization.
		$action = isset( $_REQUEST['action'] ) && is_scalar( $_REQUEST['action'] )
			? sanitize_key( (string) wp_unslash( $_REQUEST['action'] ) )
			: '';
		// phpcs:enable WordPress.Security.NonceVerification.Recommended

		return 'upload-attachment' === $action;
	}

	/**
	 * Remove object callbacks belonging to selected classes.
	 *
	 * @param string   $hook Hook name.
	 * @param string[] $classes Class names to remove.
	 */
	private static function remove_class_callbacks( string $hook, array $classes ): void {
		global $wp_filter;

		if ( empty( $wp_filter[ $hook ] ) || ! $wp_filter[ $hook ] instanceof WP_Hook ) {
			return;
		}

		foreach ( $wp_filter[ $hook ]->callbacks as $priority => $callbacks ) {
			foreach ( $callbacks as $callback ) {
				$function = $callback['function'] ?? null;
				if ( ! is_array( $function ) || empty( $function[0] ) ) {
					continue;
				}

				$class = is_object( $function[0] ) ? get_class( $function[0] ) : (string) $function[0];
				if ( in_array( $class, $classes, true ) ) {
					remove_filter( $hook, $function, $priority );
				}
			}
		}
	}
}

HS_Media_Upload_Accelerator::boot();
