import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import { DatabaseSync } from 'node:sqlite';
import test from 'node:test';
import { ReaderComments, ReaderCommentError } from '../comments-store.js';
import { ReaderProfiles } from '../profiles.js';
import { legacyPending } from './legacy-comments-fixture.js';

function setup() { const db = new DatabaseSync(':memory:'); let time = 1_000_000; const issuer = 'https://identity.example'; const profiles = new ReaderProfiles({ db, issuer, now: () => time }); const comments = new ReaderComments({ db, issuer, now: () => time }); const make = (subject, name = subject) => profiles.getOrCreate(subject, name); const input = (profile, more = {}) => ({ postId: 1, body: '  Хороший разбор!  ', parentId: null, operationId: randomUUID(), profileVersion: profile.version, attachmentId: null, ...more }); return { db, profiles, comments, make, input, tick: (n = 1) => { time += n; } }; }
const code = (fn, expected) => assert.throws(fn, error => error instanceof ReaderCommentError && error.status === expected[0] && error.code === expected[1]);

test('submits immediate comments without a separate consent checkbox and rejects spoofed fields', () => { const x = setup(); try { const alice = x.make('alice', 'Алиса'); const saved = x.comments.submit('alice', x.input(alice)); assert.equal(saved.status, 'published'); assert.equal(saved.body, 'Хороший разбор!'); code(() => x.comments.submit('alice', { ...x.input(alice), publicConsent: true }), [400, 'invalid_input']); code(() => x.comments.submit('alice', { ...x.input(alice), status: 'published' }), [400, 'invalid_input']); code(() => x.comments.submit('alice', x.input(alice, { body: 'x\u0000y' })), [400, 'invalid_input']); } finally { x.db.close(); } });
test('isolates pending comments, preserves idempotent retries, and rejects changed replays', () => { const x = setup(); try { const alice = x.make('alice', 'Алиса'); const bob = x.make('bob', 'Боб'); const request = x.input(alice); const first = legacyPending(x.comments, 'alice', request); assert.equal(x.comments.list(1).items.length, 0); assert.equal(x.comments.list(1, { viewerSubject: 'bob' }).items.length, 0); assert.equal(x.comments.list(1, { viewerSubject: 'alice' }).items[0].id, first.id); assert.equal(x.comments.submit('alice', request).author.name, 'Алиса'); code(() => x.comments.submit( 'alice', { ...request, body: 'Другое тело' }), [409, 'idempotency_conflict']); assert.equal(bob.id !== alice.id, true); } finally { x.db.close(); } });
test('counts all submissions for subject rate limits but allows a prior identical retry', () => { const x = setup(); try { const alice = x.make('alice'); const first = x.input(alice); x.comments.submit('alice', first); for (let i = 0; i < 4; i++) x.comments.submit('alice', x.input(alice)); assert.equal(x.comments.submit('alice', first).id.length > 0, true); code(() => x.comments.submit('alice', x.input(alice)), [429, 'rate_limited']); } finally { x.db.close(); } });
test('moderation CAS publishes exact profile snapshot and parents must be published one-level comments', () => { const x = setup(); try { const alice = x.make('alice', 'Алиса'); const pending = legacyPending(x.comments, 'alice', x.input(alice)); code(() => x.comments.submit( 'alice', x.input(alice, { parentId: pending.id })), [409, 'invalid_parent']); code(() => x.comments.review(pending.id, { version: 2, decision: 'publish', actor: 'mod' }), [409, 'review_conflict']); const published = x.comments.review(pending.id, { version: 1, decision: 'publish', actor: 'mod' }); assert.equal(published.status, 'published'); const reply = legacyPending(x.comments, 'alice', x.input(alice, { parentId: pending.id })); x.comments.review(reply.id, { version: 1, decision: 'publish', actor: 'mod' }); code(() => x.comments.submit( 'alice', x.input(alice, { parentId: reply.id })), [409, 'invalid_parent']); assert.deepEqual(x.comments.publicProfile(alice.id).name, 'Алиса'); } finally { x.db.close(); } });
test('profile version race cannot publish unapproved changed private fields or avatar', () => { const x = setup(); try { const alice = x.make('alice', 'Алиса'); const pending = legacyPending(x.comments, 'alice', x.input(alice)); x.profiles.update('alice', { version: 1, displayName: 'Скрытая смена', bio: 'не публиковать', favoriteClass: 'mage' }); code(() => x.comments.review(pending.id, { version: 1, decision: 'publish', actor: 'mod' }), [409, 'profile_version_conflict']); assert.equal(x.comments.publicProfile(alice.id), null); assert.equal(x.comments.publicAvatar(alice.id, 'guessed'), null); } finally { x.db.close(); } });
test('published listing exposes only snapshot DTO, deletion is idempotent and erasure removes public avatar', () => { const x = setup(); try { let alice = x.make('alice', 'Алиса'); alice = x.profiles.setAvatar('alice', Buffer.from('avatar'), alice.version); const pending = legacyPending(x.comments, 'alice', x.input(alice)); x.comments.review(pending.id, { version: 1, decision: 'publish', actor: 'mod' }); const publicProfile = x.comments.publicProfile(alice.id); assert.deepEqual(x.comments.publicAvatar(alice.id, publicProfile.avatarVersion), Buffer.from('avatar')); const row = x.comments.list(1).items[0]; assert.equal(JSON.stringify(row).includes('alice'), false); x.comments.erase('alice'); x.comments.erase('alice'); const tombstone = x.comments.list(1).items[0]; assert.deepEqual({ status: tombstone.status, body: tombstone.body, author: tombstone.author }, { status: 'deleted', body: null, author: null }); assert.equal(x.comments.publicProfile(alice.id), null); assert.equal(x.comments.publicAvatar(alice.id, publicProfile.avatarVersion), null); } finally { x.db.close(); } });
test('an erased operation cannot resurrect its body', () => { const x = setup(); try { const alice = x.make('alice'); const request = x.input(alice); x.comments.submit('alice', request); x.comments.erase('alice'); code(() => x.comments.submit('alice', request), [410, 'erased']); code(() => x.comments.submit('alice', { ...request, body: 'изменённое тело' }), [409, 'idempotency_conflict']); } finally { x.db.close(); } });
test('owners can remove exactly one comment with CAS while replies survive', () => { const x = setup(); try { const alice = x.make('alice'); const bob = x.make('bob'); const root = legacyPending(x.comments, 'alice', x.input(alice)); x.comments.review(root.id, { version: 1, decision: 'publish', actor: 'mod' }); const reply = legacyPending(x.comments, 'bob', x.input(bob, { parentId: root.id })); x.comments.review(reply.id, { version: 1, decision: 'publish', actor: 'mod' }); code(() => x.comments.remove('bob', root.id, { version: 2 }), [404, 'comment_not_found']); const deleted = x.comments.remove('alice', root.id, { version: 2 }); assert.deepEqual(deleted, { id: root.id, status: 'deleted', version: 3 }); assert.deepEqual(x.comments.remove('alice', root.id, { version: 2 }), deleted); assert.equal(x.comments.list(1).items.filter(item => item.id === reply.id).length, 1); assert.deepEqual(x.comments.metadataForComment(root.id), { postId: 1 }); } finally { x.db.close(); } });
test('issuer boundaries cover listing, parent lookup, review and public snapshots', () => { const x = setup(); try { const alice = x.make('alice'); const item = legacyPending(x.comments, 'alice', x.input(alice)); const otherProfiles = new ReaderProfiles({ db: x.db, issuer: 'https://other.example', now: () => 1_000_000 }); const other = otherProfiles.getOrCreate('alice', 'Другая'); const otherComments = new ReaderComments({ db: x.db, issuer: 'https://other.example', now: () => 1_000_000 }); code(() => otherComments.review(item.id, { version: 1, decision: 'reject', actor: 'mod' }), [409, 'review_conflict']); code(() => otherComments.submit('alice', { ...x.input(other), parentId: item.id }), [409, 'invalid_parent']); x.comments.review(item.id, { version: 1, decision: 'publish', actor: 'mod' }); assert.equal(otherComments.publicProfile(alice.id), null); assert.equal(otherComments.list(1).items.length, 0); } finally { x.db.close(); } });
test('cleanup rejects expired pending text before it can be moderated', () => { const x = setup(); try { const alice = x.make('alice'); const item = legacyPending(x.comments, 'alice', x.input(alice)); x.tick(31 * 86_400_000); assert.equal(x.comments.cleanup().comments, 1); code(() => x.comments.review(item.id, { version: 2, decision: 'publish', actor: 'mod' }), [409, 'review_conflict']); } finally { x.db.close(); } });
test('stale pending moderation is denied before cleanup and rejected text is retained only 30 days', () => { const x = setup(); try { const alice = x.make('alice'); const pending = legacyPending(x.comments, 'alice', x.input(alice)); const rejected = legacyPending(x.comments, 'alice', x.input(alice)); x.comments.review(rejected.id, { version: 1, decision: 'reject', actor: 'mod' }); x.tick(30 * 86_400_000); code(() => x.comments.review(pending.id, { version: 1, decision: 'publish', actor: 'mod' }), [409, 'review_conflict']); assert.equal(x.comments.cleanup().comments, 2); assert.equal(x.comments.ownExport('alice').items.find(item => item.id === rejected.id).body, null); } finally { x.db.close(); } });
test('published profile eligibility excludes pending-only posts and moderator takedown preserves replies', () => { const x = setup(); try { const alice = x.make('alice'); const root = legacyPending(x.comments, 'alice', x.input(alice)); assert.deepEqual(x.comments.postIdsForProfile(alice.id), []); x.comments.review(root.id, { version: 1, decision: 'publish', actor: 'mod' }); const reply = legacyPending(x.comments, 'alice', x.input(alice, { parentId: root.id })); x.comments.review(reply.id, { version: 1, decision: 'publish', actor: 'mod' }); assert.deepEqual(x.comments.postIdsForProfile(alice.id), [1]); assert.deepEqual(x.comments.moderatorRemove(root.id, { version: 2, actor: 'mod' }), { id: root.id, status: 'deleted', version: 3 }); assert.equal(x.comments.list(1).items.some(item => item.id === reply.id), true); } finally { x.db.close(); } });
test('public avatar disappears after the owner removes their last published comment', () => {
  const x = setup();
  try {
    let alice = x.make('alice');
    alice = x.profiles.setAvatar('alice', Buffer.from('avatar'), alice.version);
    const comment = legacyPending(x.comments, 'alice', x.input(alice));
    x.comments.review(comment.id, { version: 1, decision: 'publish', actor: 'mod' });
    assert.deepEqual(x.comments.publicAvatar(alice.id, alice.avatarUrl.split('=')[1]), Buffer.from('avatar'));
    x.comments.remove('alice', comment.id, { version: 2 });
    assert.equal(x.comments.publicAvatar(alice.id, alice.avatarUrl.split('=')[1]), null);
  } finally { x.db.close(); }
});

test('public avatar disappears after moderator takedown of the last published comment', () => {
  const x = setup();
  try {
    let alice = x.make('alice');
    alice = x.profiles.setAvatar('alice', Buffer.from('avatar'), alice.version);
    const comment = legacyPending(x.comments, 'alice', x.input(alice));
    x.comments.review(comment.id, { version: 1, decision: 'publish', actor: 'mod' });
    const version = alice.avatarUrl.split('=')[1];
    x.comments.moderatorRemove(comment.id, { version: 2, actor: 'mod' });
    assert.equal(x.comments.publicAvatar(alice.id, version), null);
  } finally { x.db.close(); }
});
test('pagination, own export, cleanup and internal entitlement mapping are bounded', () => { const x = setup(); try { const alice = x.make('alice'); const ids = []; for (let i = 0; i < 3; i++) { const c = legacyPending(x.comments, 'alice', x.input(alice, { body: `Текст номер ${i}` })); x.comments.review(c.id, { version: 1, decision: 'publish', actor: 'mod' }); ids.push(c.id); x.tick(); } const page = x.comments.list(1, { limit: 2 }); assert.equal(page.items.length, 2); assert.equal(x.comments.list(1, { cursor: page.nextCursor, limit: 2 }).items.length, 1); assert.equal(x.comments.ownExport('alice', { limit: 100 }).items.length, 3); assert.equal(x.comments.subjectsForProfiles([alice.id]).get(alice.id), 'alice'); code(() => x.comments.list(1, { limit: 51 }), [400, 'invalid_input']); x.tick(31 * 86_400_000); assert.equal(x.comments.cleanup().comments, 0); } finally { x.db.close(); } });
