location = /wp-content/cache/min/1/wp-content/plugins/hs-tooltip/assets/hs-tooltip.js {
    expires 1y;
    add_header Cache-Control "public, max-age=31536000, immutable" always;
    add_header Strict-Transport-Security "max-age=15552000" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header Referrer-Policy "strict-origin-when-cross-origin" always;
    add_header Permissions-Policy "camera=(), microphone=(), geolocation=(), payment=()" always;
    add_header Content-Security-Policy "frame-ancestors 'self'" always;
    access_log off;
    try_files $uri /wp-content/plugins/hs-tooltip/assets/hs-tooltip.js =404;
}

location = /wp-content/cache/min/1/wp-content/plugins/hs-tooltip/assets/hs-tooltip.css {
    expires 1y;
    add_header Cache-Control "public, max-age=31536000, immutable" always;
    add_header Strict-Transport-Security "max-age=15552000" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header Referrer-Policy "strict-origin-when-cross-origin" always;
    add_header Permissions-Policy "camera=(), microphone=(), geolocation=(), payment=()" always;
    add_header Content-Security-Policy "frame-ancestors 'self'" always;
    access_log off;
    try_files $uri /wp-content/plugins/hs-tooltip/assets/hs-tooltip.css =404;
}
