location = /fpm-status-hs-manacost {
    allow 127.0.0.1;
    allow ::1;
    allow 151.80.21.140;
    deny all;

    access_log off;
    include fastcgi_params;
    fastcgi_pass unix:/var/www/php-fpm/hs-manacost-php84.sock;
}

location = /fpm-ping-hs-manacost {
    allow 127.0.0.1;
    allow ::1;
    allow 151.80.21.140;
    deny all;

    access_log off;
    include fastcgi_params;
    fastcgi_pass unix:/var/www/php-fpm/hs-manacost-php84.sock;
}
